### ISSUE TITLE
There are no shaderVert.c and shaderFrag.c files in chapter 08

### ISSUE THREAD

**Issue by logic1988** [firmread/ofDemystified#4]
I found that there are no shaderVert.c and shaderFrag.c files in all examples of chapter 08. 
Excuse me if it is convenient for you to upload these files?

**Comment by firmread** [comment]
I won't be able to fix this anytime soon. I'm not sure how it lost in the process, but if you dig into the first commit of this repo, those shader files are still there. 

Also feel free to send me PR if you got them back to the right place! 

Cheers,
Reed

**Comment by logic1988** [comment]
Thank you very much! I got it.
